clc; clear all;
Ip = imread('./Pictures/reflect/0c_cr.jpg');
Io = imread('./Pictures/reflect/90c_cr.jpg');
Ip = double(Ip);
Io = double(Io);
Itotal = Ip + Io;
Icontr = Ip - Io;
Iratio = (Ip - Io) ./ (Ip + Io);
%figure(), imagesc(Itotal);
%figure(), imagesc(abs(Icontr));
%figure(), imagesc(Iratio);
%colormap(gray);

Ip = imread('./Pictures/reflect/d90.jpg');
Io = imread('./Pictures/reflect/d0.jpg');
Ip = double(Ip);
Io = double(Io);
Itotal = Ip + Io;
Icontr = Ip - Io;
Itotal(Itotal == 0) = 1;
Iratio = Icontr ./ Itotal;
figure(), imagesc(Itotal);
figure(), imagesc((Icontr));
figure(), imagesc((Iratio));
colormap(gray);
